# Generated by Django 5.1.7 on 2025-06-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_contact_delete_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='branch',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='college_name',
            field=models.CharField(default='NaN', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='course',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
