# Generated by Django 5.1.7 on 2025-06-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_contact_branch_contact_college_name_contact_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='branch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='college_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
